In [ ]:
import eurostat
import pandas as pd
df = eurostat.get_data_df("tps00206") # marriage rate
df.head()

,freq,indic_de,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,GNUPRT,AD,NaN,NaN,NaN,NaN,NaN,3.9,NaN,NaN,NaN,NaN,NaN,NaN
1,A,GNUPRT,AL,8.2,8.2,8.7,7.8,7.9,8.1,7.9,6.2,7.0,6.8,NaN,6.8
2,A,GNUPRT,AM,NaN,NaN,5.9,5.4,5.1,5.0,5.3,NaN,NaN,NaN,5.5,NaN
3,A,GNUPRT,AT,4.3,4.4,5.1,5.1,5.1,5.3,5.2,4.4,NaN,NaN,5.0,5.0
4,A,GNUPRT,AZ,9.2,8.9,7.1,6.8,6.4,6.3,6.4,NaN,NaN,6.1,NaN,NaN

In [19]:
import eurostat
import pandas as pd
df = eurostat.get_data_df("tps00014") # age at first marriage
df = df.sort_values(["geo\\TIME_PERIOD"])
df['indic_de'].unique()

<ArrowStringArray>
['FAGEMAR1', 'MAGEMAR1']
Length: 2, dtype: str

In [ ]:
import eurostat
import pandas as pd
df = eurostat.get_data_df("tessi180") # income quintiles
df.head()

,freq,age,sex,unit,geo\TIME_PERIOD,2005,2006,2007,2008,2009,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,A,TOTAL,F,RAT,AL,NaN,NaN,NaN,NaN,NaN,...,NaN,7.50,7.05,6.37,5.86,5.72,5.09,4.85,NaN,NaN
1,A,TOTAL,F,RAT,AT,3.80,3.72,3.80,4.16,4.11,...,3.98,4.35,4.01,4.14,4.04,4.04,4.17,4.19,4.27,NaN
2,A,TOTAL,F,RAT,BE,3.78,3.97,3.84,4.06,3.89,...,3.75,3.80,3.73,3.54,3.56,3.36,3.46,3.35,3.38,3.19
3,A,TOTAL,F,RAT,BG,NaN,5.09,6.95,6.48,5.96,...,7.43,8.00,7.41,7.75,7.87,7.54,7.20,6.23,6.56,6.71
4,A,TOTAL,F,RAT,CH,NaN,NaN,4.65,4.87,4.75,...,4.29,4.37,4.27,4.50,4.73,4.64,4.75,4.83,4.69,NaN

In [ ]:
import eurostat
import pandas as pd
df = eurostat.get_data_df("tps00216") # divorce rate
df.head()

,freq,indic_de,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,GDIVRT,AL,NaN,1.5,1.3,1.9,1.6,1.7,2.1,1.5,1.1,NaN,NaN,2.0
1,A,GDIVRT,AM,NaN,NaN,1.2,1.2,NaN,1.3,1.3,1.1,NaN,NaN,1.5,NaN
2,A,GDIVRT,AT,1.9,1.9,1.9,1.8,1.8,1.8,1.8,1.7,1.6,1.5,1.6,1.6
3,A,GDIVRT,AZ,1.2,1.3,1.3,1.3,1.5,1.5,1.7,1.4,NaN,1.6,NaN,NaN
4,A,GDIVRT,BE,2.2,2.2,2.2,2.1,2.0,2.0,2.0,1.8,1.9,1.7,1.7,NaN

In [21]:
# Testing if bruin did write correctly to duckdb
import duckdb

with duckdb.connect(database='./data/duckdb.db') as conn:
    # print(conn.execute("SELECT * FROM information_schema.schemata").df())
    for table in ["load.divorce_rate", "load.age_at_marriage", "load.income_quintile","load.marriage_rate"]:
        print(f"\n--- {table} ---")
        display(conn.execute(f"SELECT * FROM {table} ORDER BY country, year LIMIT 10").df())
    print(conn.execute("SELECT * FROM analytics.relationships ORDER BY country, year LIMIT 20 ").df())

--- load.divorce_rate ---

  country  year  divorce_rate
0      AL  2014           1.5
1      AL  2015           1.3
2      AL  2016           1.9
3      AL  2017           1.6
4      AL  2018           1.7
5      AL  2019           2.1
6      AL  2020           1.5
7      AL  2021           1.1
8      AL  2024           2.0
9      AM  2015           1.2

--- load.age_at_marriage ---

   indic_de country  year  age_at_marriage
0  FAGEMAR1      AM  2015             26.8
1  MAGEMAR1      AM  2015             30.8
2  FAGEMAR1      AM  2017             26.7
3  MAGEMAR1      AM  2017             31.0
4  FAGEMAR1      AM  2018             26.7
5  MAGEMAR1      AM  2018             31.0
6  FAGEMAR1      AT  2013             30.7
7  MAGEMAR1      AT  2013             33.3
8  FAGEMAR1      AT  2014             30.9
9  MAGEMAR1      AT  2014             33.6

--- load.income_quintile ---

  country  year sex  income_quintile
0      AL  2017   F             7.50
1      AL  2017   M             7.44
2      AL  2018   F             7.05
3      AL  2018   M             6.93
4      AL  2019   F             6.37
5      AL  2019   M             6.36
6      AL  2020   F             5.86
7      AL  2020   M             5.92
8      AL  2021   F             5.72
9      AL  2021   M             5.73

--- load.marriage_rate ---

  country  year  marriage_rate
0      AD  2018            3.9
1      AL  2013            8.2
2      AL  2014            8.2
3      AL  2015            8.7
4      AL  2016            7.8
5      AL  2017            7.9
6      AL  2018            8.1
7      AL  2019            7.9
8      AL  2020            6.2
9      AL  2021            7.0

   country  year  marriage_rate  divorce_rate  age_at_marriage_f  \
0       AD  2018            3.9           NaN                NaN
1       AL  2013            8.2           NaN                NaN
2       AL  2014            8.2           1.5                NaN
3       AL  2015            8.7           1.3                NaN
4       AL  2016            7.8           1.9                NaN
5       AL  2017            7.9           1.6                NaN
6       AL  2018            8.1           1.7                NaN
7       AL  2019            7.9           2.1                NaN
8       AL  2020            6.2           1.5                NaN
9       AL  2021            7.0           1.1                NaN
10      AL  2022            6.8           NaN                NaN
11      AL  2024            6.8           2.0                NaN
12      AM  2015            5.9           1.2               26.8
13      AM  2016            5.4           1.2                NaN
14      AM  2017            5.1           NaN               26.7
15      AM  2018            5.0           1.3               26.7
16      AM  2019            5.3           1.3                NaN
17      AM  2023            5.5           1.5                NaN
18      AT  2013            4.3           1.9               30.7
19      AT  2014            4.4           1.9               30.9

    age_at_marriage_m  income_quintile_f  income_quintile_m
0                 NaN                NaN                NaN
1                 NaN                NaN                NaN
2                 NaN                NaN                NaN
3                 NaN                NaN                NaN
4                 NaN                NaN                NaN
5                 NaN               7.50               7.44
6                 NaN               7.05               6.93
7                 NaN               6.37               6.36
8                 NaN               5.86               5.92
9                 NaN               5.72               5.73
10                NaN               5.09               5.14
11                NaN                NaN                NaN
12               30.8                NaN                NaN
13                NaN                NaN                NaN
14               31.0                NaN                NaN
15               31.0                NaN                NaN
16                NaN                NaN                NaN
17                NaN                NaN                NaN
18               33.3               4.12               4.11
19               33.6               4.14               4.11